#!/usr/bin/perl
use strict;
use warnings;

$ENV{CLK_ROOT} ||= './play';

# the user must identify himself
die "Please set CLK_IDENTITY to indicate who you are.\n"
  . "For example:\n"
  . "\n"
  . "  export CLK_IDENTITY=somebody\@example.com\n"
  if not defined $ENV{CLK_IDENTITY};

# if testing, put the current directory in the path
$ENV{PATH} = ".:$ENV{PATH}" if substr($0, 0, 1) eq '.';

my $command = shift or die "Please specfy a clk command\n";

exec "clk-$command", @ARGV;
