#!/usr/bin/perl
use strict;
use warnings;

# adjust the environment, if necessary
my $bin_dir = '/Users/michael/src/clk';  # TODO fill this in at build time
if ( not $ENV{CLK_ENVIRONMENT_ALREADY_ADJUSTED} ) {
    $ENV{CLK_ROOT} ||= './play';
    $ENV{PERL5LIB}   = "$bin_dir/lib:" . ( $ENV{PERL5LIB} || '' );
    $ENV{PATH}       = $bin_dir . ':' . ( $ENV{PATH} || '' );
    $ENV{CLK_ENVIRONMENT_ALREADY_ADJUSTED} = 1;
}

# the user must identify himself
die "Please set CLK_IDENTITY to indicate who you are.\n"
  . "For example:\n"
  . "\n"
  . "  export CLK_IDENTITY=somebody\@example.com\n"
  if not defined $ENV{CLK_IDENTITY};

my $command = shift or die "Please specfy a clk command\n";

exec "clk-$command", @ARGV;
