#!/usr/bin/perl
use strict;
use warnings;

( my $clk_in = $0 ) =~ s/clk-out/clk-in/;
exec $clk_in, 'out', @ARGV;

__END__

=head1 NAME

clk-out - Stop recording time for a task

=head1 SYNOPSIS

B<clk out>

=head1 DESCRIPTION

This is identical to invoking C<clk in out>, but semantically is the
opposite of C<clk in>.  Use this command to stop recording time
for a particular task.

=head1 OPTIONS

See C<clk-out>.

=head1 HOOKS

See C<clk-out>.

=head1 EXIT CODES

See C<clk-out>.
