#!/usr/bin/perl
use strict;
use warnings;
use App::Clk::Report;
use POSIX qw( strftime );

my $rpt = Report->new(@ARGV);
while ( my $entry = $rpt->next ) {
    my $time = to_localtime($entry->{time});
    printf "%6s %5s %5s %s\n",
        abbreviated_entry_id($entry->{id}),
        nice_date($time),
        nice_time($time),
        $entry->{text};
}

sub abbreviated_entry_id {
    my ($id) = @_;
    return substr $id, 0, 6;
}

sub nice_date {
    my ($epoch) = @_;
    return strftime("%m/%d", localtime($epoch) );
}

sub nice_time {
    my ($epoch) = @_;
    return strftime("%H:%M", localtime($epoch) );
}
